// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Relude_ReaderT from "relude/src/Relude_ReaderT.mjs";

function log(prim) {
  console.log(prim);
}

function log2(prim0, prim1) {
  console.log(prim0, prim1);
}

var testEnv = {
  version: 42,
  product: "relude"
};

var Reader = Relude_ReaderT.Reader.WithEnv({});

var prim = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })(Reader.make(function (r) {
          return (r.version << 1);
        }));

console.log(prim);

var prim$1 = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })((function (__x) {
          return Reader.map((function (a) {
                        return a.version;
                      }), __x);
        })(Reader.ask));

console.log(prim$1);

var prim$2 = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })((function (__x) {
          return Reader.map((function (a) {
                        return Math.imul(a, 10);
                      }), __x);
        })(Reader.asks(function (r) {
              return (r.version << 1);
            })));

console.log(prim$2);

var prim$3 = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })(Reader.local((function (r) {
            return {
                    version: (r.version << 1),
                    product: r.product + "!"
                  };
          }), (function (__x) {
              return Reader.map((function (a) {
                            return String(a.version) + a.product;
                          }), __x);
            })(Reader.ask)));

console.log(prim$3);

var prim$4 = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })((function (__x) {
          return Reader.map((function (a) {
                        return (a << 1);
                      }), __x);
        })(Reader.pure(42)));

console.log(prim$4);

var prim$5 = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })((function (__x) {
          return Reader.apply(Reader.make(function (r) {
                          return function (a) {
                            return (Math.imul(a, r.version) << 1);
                          };
                        }), __x);
        })(Reader.pure(42)));

console.log(prim$5);

var prim$6 = (function (__x) {
      return Reader.runReaderT(testEnv, __x);
    })((function (__x) {
          return Reader.flatMap((function (a) {
                        return Reader.make(function (r) {
                                    return Math.imul(r.version, a);
                                  });
                      }), __x);
        })(Reader.pure(42)));

console.log(prim$6);

var ReaderT;

export {
  ReaderT ,
  log ,
  log2 ,
  testEnv ,
  Reader ,
}
/* Reader Not a pure module */
