// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

function is_empty(list) {
  if (list) {
    return false;
  } else {
    return true;
  }
}

function push(x, list) {
  return {
          hd: x,
          tl: list
        };
}

var Empty = /* @__PURE__ */Caml_exceptions.create("OP_CH05_2_List_Stack.ListStack.Empty");

function peek(list) {
  if (list) {
    return list.hd;
  }
  throw {
        RE_EXN_ID: Empty,
        Error: new Error()
      };
}

function pop(list) {
  if (list) {
    return list.tl;
  }
  throw {
        RE_EXN_ID: Empty,
        Error: new Error()
      };
}

var ListStack = {
  Empty: Empty,
  empty: /* [] */0,
  is_empty: is_empty,
  push: push,
  peek: peek,
  pop: pop
};

var M = {
  x: 42
};

var Inner = {
  x: 42
};

var M_ = {
  Inner: Inner
};

var M$1 = {
  x: 0,
  z: 2
};

var M_5_2_4_MZ = {
  z: 2
};

var M_5_2_4 = {
  M: M$1,
  MX: M$1,
  MZ: M_5_2_4_MZ,
  MXZ: M$1
};

function f(x) {
  return x;
}

var IdFun = {
  f: f
};

var A = {
  a: 0
};

var AB = {
  a: 0,
  b: true
};

var AC = {
  a: 0,
  c: /* 'c' */99
};

var EX_1 = {
  A: A,
  AB: AB,
  AC: AC
};

var ListStackAlias = ListStack;

var Iid = IdFun;

export {
  ListStack ,
  ListStackAlias ,
  M ,
  M_ ,
  M_5_2_4 ,
  IdFun ,
  Iid ,
  EX_1 ,
  
}
/* No side effect */
