// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hashtbl from "rescript/lib/es6/hashtbl.js";

var T_module_name = "Bap.Std.Type";

var T = {
  module_name: T_module_name,
  version: "1.0.0",
  hash: Hashtbl.hash
};

export {
  T ,
}
/* No side effect */
