// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/Belt_Id.js";
import * as Belt_MutableMap from "rescript/lib/es6/Belt_MutableMap.js";

function cmp(m1, m2) {
  return m1 - m2 | 0;
}

let M = {
  cmp: cmp
};

let M_Id = Belt_Id.MakeComparableU(M);

let map = Belt_MutableMap.make(M_Id);

Belt_MutableMap.set(map, 1, "a");

let M1 = {};

let M1_Id = Belt_Id.comparable((m1, m2) => m1 - m2 | 0);

let map$1 = Belt_MutableMap.make(M1_Id);

Belt_MutableMap.set(map$1, 1, "a");

function add(a, b) {
  return a + b | 0;
}

let a = {
  add: add
};

let B = a;

export {
  M,
  M_Id,
  M1,
  M1_Id,
  map$1 as map,
  a,
  B,
}
/* M_Id Not a pure module */
