// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_MutableMap from "rescript/lib/es6/belt_MutableMap.js";

function cmp(m1, m2) {
  return m1 - m2 | 0;
}

var M = {
  cmp: cmp
};

var M_Id = Belt_Id.MakeComparableU(M);

var map = Belt_MutableMap.make(M_Id);

Belt_MutableMap.set(map, 1, "a");

var M1 = {};

var M1_Id = Belt_Id.comparable(function (m1, m2) {
      return m1 - m2 | 0;
    });

var map$1 = Belt_MutableMap.make(M1_Id);

Belt_MutableMap.set(map$1, 1, "a");

function add(a, b) {
  return a + b | 0;
}

var a = {
  add: add
};

var B = a;

export {
  M ,
  M_Id ,
  M1 ,
  M1_Id ,
  map$1 as map,
  a ,
  B ,
}
/* M_Id Not a pure module */
