// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function run(r, env) {
  return Curry._1(r._0, env);
}

function $$return(a) {
  return /* Reader */{
          _0: (function (_env) {
              return a;
            })
        };
}

function ask(param) {
  return /* Reader */{
          _0: (function (env) {
              return env;
            })
        };
}

function local(f, m) {
  return /* Reader */{
          _0: (function (env) {
              return run(m, Curry._1(f, env));
            })
        };
}

function map(f, m) {
  return /* Reader */{
          _0: (function (env) {
              return Curry._1(f, run(m, env));
            })
        };
}

function bind(f, m) {
  return /* Reader */{
          _0: (function (env) {
              return run(Curry._1(f, run(m, env)), env);
            })
        };
}

function bindFlip(m, f) {
  return bind(f, m);
}

function _getState(env2) {
  return env2.state;
}

var __x = /* Reader */{
  _0: (function (_env) {
      return "danny";
    })
};

var r2 = bind((function (x) {
        var __x = map(_getState, /* Reader */{
              _0: (function (env) {
                  return env;
                })
            });
        return map((function (y) {
                      return String(y) + x;
                    }), __x);
      }), __x);

console.log(run(r2, {
          state: 1
        }));

console.log(run(r2, {
          state: 3
        }));

export {
  run ,
  $$return ,
  ask ,
  local ,
  map ,
  bind ,
  bindFlip ,
}
/* r2 Not a pure module */
