// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function square(x) {
  let result = x * x | 0;
  return {
    result: result,
    logs: [`Squared ` + x.toString() + ` to get ` + result.toString()]
  };
}

function addOne(x) {
  let result = x + 1 | 0;
  return {
    result: result,
    logs: [`Added 1 to ` + x.toString() + ` to get to ` + result.toString()]
  };
}

function wrapWithLog(x) {
  return {
    result: x,
    logs: []
  };
}

function runWithLogs(input, transform) {
  let resultWithLogs = transform(input.result);
  return {
    result: resultWithLogs.result,
    logs: Belt_Array.concat(input.logs, resultWithLogs.logs)
  };
}

let a_logs = [];

let a = {
  result: 5,
  logs: a_logs
};

let b = runWithLogs(a, addOne);

console.log(runWithLogs(b, square));

let peter = "Peter";

function isABoy(x) {
  return x.concat(" is a boy");
}

console.log(Belt_Option.flatMap(peter, isABoy));

console.log(Belt_Option.flatMap(undefined, isABoy));

let noone;

export {
  square,
  addOne,
  wrapWithLog,
  runWithLogs,
  a,
  b,
  peter,
  noone,
  isABoy,
}
/* b Not a pure module */
