// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";

function evalWith5ThenAdd2(fn) {
  return Curry._1(fn, 5) + 2 | 0;
}

console.log(8);

function times3(x) {
  return Math.imul(x, 3);
}

console.log(17);

function add(x, y) {
  return x + y | 0;
}

function add1(param) {
  return 1 + param | 0;
}

function add2(param) {
  return 2 + param | 0;
}

console.log(6);

console.log(7);

function evalWith5AsInt(fn) {
  return Curry._1(fn, 5);
}

function evalWith5AsFloat(fn) {
  return Curry._1(fn, 5);
}

function evalWith5AsString(fn) {
  return fn + "5";
}

function printInt(x) {
  console.log("x is " + String(x));
  
}

console.log("hello world");

function printHelloFn(param) {
  console.log("hello world");
  
}

console.log(printHelloFn);

console.log((console.log("hello world"), undefined));

function toString(x) {
  return String(x._0);
}

function onAStick(x) {
  return String(x._0) + " on a stick";
}

console.log(String(1) + " on a stick");

console.log(String(2.0) + " on a stick");

function multiParamFn(p1, p2, p3, p4) {
  
}

function intermediateFn1(param, param$1, param$2) {
  
}

function intermediateFn2(param, param$1) {
  return intermediateFn1(false, param, param$1);
}

function intermediateFn3(param) {
  return intermediateFn1(false, "hello", param);
}

var finalResult = intermediateFn1(false, "hello", 3.141);

var whatIsThis;

var printHello;

var a = [
  "hello",
  1
];

export {
  evalWith5ThenAdd2 ,
  times3 ,
  add ,
  add1 ,
  add2 ,
  evalWith5AsInt ,
  evalWith5AsFloat ,
  evalWith5AsString ,
  whatIsThis ,
  printInt ,
  printHello ,
  printHelloFn ,
  toString ,
  onAStick ,
  a ,
  multiParamFn ,
  intermediateFn1 ,
  intermediateFn2 ,
  intermediateFn3 ,
  finalResult ,
  
}
/*  Not a pure module */
