// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "rescript/lib/es6/list.js";

function is_empty(param) {
  return param[0] === /* [] */0;
}

function add(queue, elt) {
  var prefix = queue[0];
  if (prefix || queue[1]) {
    return [
            prefix,
            {
              hd: elt,
              tl: queue[1]
            }
          ];
  } else {
    return [
            {
              hd: elt,
              tl: /* [] */0
            },
            /* [] */0
          ];
  }
}

function head(param) {
  var match = param[0];
  if (match) {
    return match.hd;
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

function tail(param) {
  var match = param[0];
  if (match) {
    var prefix = match.tl;
    if (prefix) {
      return [
              prefix,
              param[1]
            ];
    } else {
      return [
              List.rev(param[1]),
              /* [] */0
            ];
    }
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

var empty = [
  /* [] */0,
  /* [] */0
];

export {
  empty ,
  is_empty ,
  add ,
  head ,
  tail ,
  
}
/* No side effect */
