// Generated by ReScript, PLEASE EDIT WITH CARE


function asyncGetInt(extra) {
  return async((function (num) {
                return num;
              }), extra);
}

function asyncSum(extra, extra$1) {
  return async((function (x, y) {
                return String(x + y | 0);
              }), extra, extra$1);
}

function asyncProg(extra) {
  return async(function () {
              var a = await(async((function (num) {
                          return num;
                        }), 5));
              var b = await(async((function (num) {
                          return num;
                        }), 10));
              var c = await(asyncSum(a, b));
              console.log(c);
            });
}

export {
  asyncGetInt ,
  asyncSum ,
  asyncProg ,
}
/* No side effect */
