// Generated by ReScript, PLEASE EDIT WITH CARE


var name2 = "Jim";

var name1 = "Joe";

console.log(name1, 23);

console.log(name2, 31);

var joe = /* Person */{
  _0: "Joe",
  _1: 23
};

var jim = /* Person */{
  _0: "Jim",
  _1: 31
};

var age1 = 23;

var age2 = 31;

export {
  joe ,
  jim ,
  name1 ,
  age1 ,
  name2 ,
  age2 ,
}
/*  Not a pure module */
