// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var name2 = "Jim";

var name1 = "Joe";

console.log(name1, 23);

console.log(name2, 31);

var joe = /* Person */{
  _0: "Joe",
  _1: 23
};

var jim = /* Person */{
  _0: "Jim",
  _1: 31
};

var age1 = 23;

var age2 = 31;

exports.joe = joe;
exports.jim = jim;
exports.name1 = name1;
exports.age1 = age1;
exports.name2 = name2;
exports.age2 = age2;
/*  Not a pure module */
