// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

function safeParse1(string) {
  try {
    var json = JSON.parse(string);
    return {
            TAG: /* Ok */0,
            _0: json
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var m = obj._1.message;
      if (m !== undefined) {
        return {
                TAG: /* Error */1,
                _0: m
              };
      } else {
        return {
                TAG: /* Error */1,
                _0: "Unknown"
              };
      }
    }
    throw obj;
  }
}

function safeParse(string) {
  var json;
  try {
    json = JSON.parse(string);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: /* Error */1,
              _0: Belt_Option.getWithDefault(exn._1.message, "Unknown")
            };
    }
    throw exn;
  }
  return {
          TAG: /* Ok */0,
          _0: json
        };
}

exports.safeParse1 = safeParse1;
exports.safeParse = safeParse;
/* No side effect */
