// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


/*
   * this js function will work under both [string] and [float]
   */
  function add (x,y){
    return x + y;
  }
;

console.log(add(3.0, 2.0));

console.log(add("hello, ", "BuckleScript"));

var x = {
  TAG: /* JsonString */1,
  _0: "hello"
};

var y = {
  TAG: /* JsonBool */0,
  _0: true
};

exports.x = x;
exports.y = y;
/*  Not a pure module */
