// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function mapOption$p(f, opt) {
  if (opt) {
    return /* Some' */{
            _0: Curry._1(f, opt._0)
          };
  } else {
    return /* None' */0;
  }
}

var a = /* Some' */{
  _0: 5
};

function inc(x) {
  return x + 1 | 0;
}

var c = mapOption$p(inc, a);

var d = mapOption$p(inc, /* None' */0);

function $$eval(a) {
  return a.VAL;
}

var myInt = 42;

var myFloat = 4.2;

var myBool = false;

var myStr = "Hello";

var b = /* None' */0;

exports.mapOption$p = mapOption$p;
exports.a = a;
exports.b = b;
exports.inc = inc;
exports.c = c;
exports.d = d;
exports.$$eval = $$eval;
exports.myInt = myInt;
exports.myFloat = myFloat;
exports.myBool = myBool;
exports.myStr = myStr;
/* c Not a pure module */
