// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "@rescript/runtime/lib/es6/Belt_Id.js";
import * as Belt_Map from "@rescript/runtime/lib/es6/Belt_Map.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function make(x) {
  return x;
}

function getValue(t) {
  return t;
}

let cmp = Primitive_object.compare;

let SomeId = {
  make: make,
  getValue: getValue,
  cmp: cmp
};

let SomeIdCmp = Belt_Id.MakeComparable({
  cmp: cmp
});

let empty = Belt_Map.make(SomeIdCmp);

let someId = 1;

let map = Belt_Map.set(empty, someId, "hello");

export {
  SomeId,
  SomeIdCmp,
  empty,
  someId,
  map,
}
/* SomeIdCmp Not a pure module */
