// Generated by ReScript, PLEASE EDIT WITH CARE


function show(person) {
  return person.name;
}

var ShowPerson = {
  show: show
};

console.log("Joe");

var joe = {
  name: "Joe"
};

export {
  ShowPerson ,
  joe ,
}
/*  Not a pure module */
