// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function show(person) {
  return person.name;
}

var ShowPerson = {
  show: show
};

console.log("Joe");

var joe = {
  name: "Joe"
};

exports.ShowPerson = ShowPerson;
exports.joe = joe;
/*  Not a pure module */
