// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function run(r, env) {
  return Curry._1(r._0, env);
}

function $$return(a) {
  return /* Reader */{
          _0: (function (_env) {
              return a;
            })
        };
}

function ask(param) {
  return /* Reader */{
          _0: (function (env) {
              return env;
            })
        };
}

function local(f, m) {
  return /* Reader */{
          _0: (function (env) {
              return run(m, Curry._1(f, env));
            })
        };
}

function map(f, m) {
  return /* Reader */{
          _0: (function (env) {
              return Curry._1(f, run(m, env));
            })
        };
}

function bind(f, m) {
  return /* Reader */{
          _0: (function (env) {
              return run(Curry._1(f, run(m, env)), env);
            })
        };
}

function bindFlip(m, f) {
  return bind(f, m);
}

exports.run = run;
exports.$$return = $$return;
exports.ask = ask;
exports.local = local;
exports.map = map;
exports.bind = bind;
exports.bindFlip = bindFlip;
/* No side effect */
