// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Result from "../node_modules/rescript/lib/es6/belt_Result.js";
import * as SafeReadFile from "./safeReadFile";

function produce(a, b) {
  return Promise.all([
              a,
              b
            ]);
}

function map(p, f) {
  return p.then(function (v) {
              return Promise.resolve(Curry._1(f, v));
            });
}

function concatContent(c1, c2) {
  if (c1 !== undefined) {
    if (c2 !== undefined) {
      return c1 + c2;
    } else {
      return c1;
    }
  } else if (c2 !== undefined) {
    return c2;
  } else {
    return ;
  }
}

function readAndConcatFiles(f1, f2) {
  return map(map(Promise.all([
                      f1,
                      f2
                    ]), (function (param) {
                    return concatContent(param[0], param[1]);
                  })), (function (c) {
                console.log(c);
                
              }));
}

function safeReadFile(prim) {
  return SafeReadFile(prim);
}

readAndConcatFiles(SafeReadFile("Color.res"), SafeReadFile("Result.res"));

console.log("=========");

function product(r1, r2) {
  if (r1.TAG === /* Ok */0) {
    if (r2.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: [
                r1._0,
                r2._0
              ]
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: r2._0
            };
    }
  } else {
    return {
            TAG: /* Error */1,
            _0: r1._0
          };
  }
}

var Result = {
  product: product
};

var maybeCityId = {
  TAG: /* Ok */0,
  _0: 1
};

var maybeTargetUser = {
  TAG: /* Ok */0,
  _0: 2
};

var maybeBookingIds = {
  TAG: /* Ok */0,
  _0: 3
};

Belt_Result.map(Belt_Result.map(product(product(maybeCityId, maybeTargetUser), maybeBookingIds), (function (param) {
            var match = param[0];
            return {
                    cityId: match[0],
                    targetUser: match[1],
                    bookingIds: param[1]
                  };
          })), (function (t) {
        console.log(t);
        
      }));

console.log("=========");

export {
  produce ,
  map ,
  concatContent ,
  readAndConcatFiles ,
  safeReadFile ,
  Result ,
  maybeCityId ,
  maybeTargetUser ,
  maybeBookingIds ,
  
}
/*  Not a pure module */
