// Generated by ReScript, PLEASE EDIT WITH CARE

import Ms from "ms";

function fromMSLong(s) {
  return Ms(s, {
              long: true
            });
}

export {
  fromMSLong ,
}
/* ms Not a pure module */
