// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function dup(x) {
  return [
          x,
          x
        ];
}

var src = [
  2,
  4,
  6
];

function flatMap(m, f) {
  return Belt_Array.reduce(m, [], (function (a, x) {
                return Belt_Array.concat(a, Curry._1(f, x));
              }));
}

console.log(Belt_Array.map(src, dup));

console.log(flatMap(src, dup));

function dupl(x) {
  return {
          hd: x,
          tl: {
            hd: x,
            tl: /* [] */0
          }
        };
}

var srcl = {
  hd: 2,
  tl: {
    hd: 4,
    tl: {
      hd: 6,
      tl: /* [] */0
    }
  }
};

function flatMapL(m, f) {
  return Belt_List.reduce(m, /* [] */0, (function (a, x) {
                return Belt_List.concat(a, Curry._1(f, x));
              }));
}

console.log(Belt_List.toArray(Belt_List.map(srcl, dupl)));

console.log(Belt_List.toArray(flatMapL(srcl, dupl)));

export {
  dup ,
  src ,
  flatMap ,
  dupl ,
  srcl ,
  flatMapL ,
  
}
/*  Not a pure module */
