// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f(x) {
  return "hello";
}

console.log("hello");

console.log({
      NAME: "BusinessErr",
      VAL: "no way"
    });

exports.f = f;
/*  Not a pure module */
