// Generated by ReScript, PLEASE EDIT WITH CARE


function MakeAtomExternals(T) {
  var Sync = {};
  var Async = {};
  return {
          Sync: Sync,
          Async: Async
        };
}

var Sync = {};

var Async = {};

var Int = {
  Sync: Sync,
  Async: Async
};

var Sync$1 = {};

var Async$1 = {};

var $$String = {
  Sync: Sync$1,
  Async: Async$1
};

var Sync$2 = {};

var Async$2 = {};

var Float = {
  Sync: Sync$2,
  Async: Async$2
};

var Sync$3 = {};

var Async$3 = {};

var IntArray = {
  Sync: Sync$3,
  Async: Async$3
};

var Atom = {
  MakeAtomExternals: MakeAtomExternals,
  Int: Int,
  $$String: $$String,
  Float: Float,
  IntArray: IntArray
};

var x = useAtom(atom([
          1,
          2,
          3
        ]));

var y = useAtom(atom(Promise.resolve([
              1,
              2,
              3
            ])));

var x$p = useAtom(atom(async function () {
          return "yo";
        }));

var y$p = useAtom(atom(function () {
          return "yo";
        }));

var T = {};

var Sync$4 = {};

var Async$4 = {};

var Atom$1 = {
  Sync: Sync$4,
  Async: Async$4
};

var Person = {
  T: T,
  Atom: Atom$1
};

var person = useAtom(atom(Promise.resolve({
              name: "Ryan",
              age: 35
            })));

export {
  Atom ,
  x ,
  y ,
  x$p ,
  y$p ,
  Person ,
  person ,
}
/* x Not a pure module */
