// Generated by ReScript, PLEASE EDIT WITH CARE


function make(s) {
  return s;
}

let Username = {
  make: make
};

function make$1(s) {
  return s;
}

let Password = {
  make: make$1
};

function f(u, pw) {
  console.log(u);
  console.log(pw);
}

let u1 = "dsiu";

let p1 = "diu";

f(u1, p1);

export {
  Username,
  Password,
  f,
  u1,
  p1,
}
/*  Not a pure module */
