// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function render(myColor) {
  if (myColor === "green" || myColor === "red") {
    console.log("Hello other colors");
  } else {
    console.log("Hello blue!");
  }
  
}

function render1(myColor) {
  if (myColor === "yellow") {
    console.log("Hello yellow!");
  } else if (myColor === "green") {
    console.log("Hello green!");
  } else {
    console.log("Hello blue!");
  }
  
}

console.log("This red-ish");

console.log("This is red-ish");

function displayColor(v) {
  if (v === "white") {
    return "Hey white!";
  } else if (v === "red") {
    return "Hello red";
  } else if (v === "green") {
    return "Hello green";
  } else {
    return "Hey blue!";
  }
}

console.log(displayColor("blue"));

var intl = Intl.NumberFormat("de-DE");

var message = "Hello Apple";

var myLabel = "aria-hidden";

var myNumber = 7;

var me = {
  NAME: "Instagram",
  VAL: "Jenny"
};

var him = {
  NAME: "Facebook",
  VAL: [
    "Josh",
    26
  ]
};

var myColor = "blue";

var basic = "Red";

var foreground = "Green";

var background = "Red";

var color = "Purple";

var theCompany = "Apple";

exports.myLabel = myLabel;
exports.myNumber = myNumber;
exports.render = render;
exports.render1 = render1;
exports.me = me;
exports.him = him;
exports.myColor = myColor;
exports.displayColor = displayColor;
exports.intl = intl;
exports.basic = basic;
exports.foreground = foreground;
exports.background = background;
exports.color = color;
exports.theCompany = theCompany;
exports.message = message;
/*  Not a pure module */
