// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";

function map_pair(r, param) {
  return [
          Curry._1(r, param[0]),
          Curry._1(r, param[1])
        ];
}

var array = [
  3,
  "a"
];

function number(v) {
  return v;
}

function string(v) {
  return v;
}

function classify(v) {
  if (typeof v === "number") {
    return {
            TAG: /* Number */0,
            _0: v
          };
  } else {
    return {
            TAG: /* String */1,
            _0: v
          };
  }
}

var Number_or_string = {
  number: number,
  string: string,
  classify: classify
};

var b = "hello";

var c = [
  3.14,
  b
];

Belt_Array.map(c, (function (x) {
        console.log(x);
        
      }));

function a(v) {
  return v;
}

function b$1(v) {
  return v;
}

var $$instanceof = (function(a) {
      return  a instanceof globalThis.A;
      });

function classify$1(v) {
  if ($$instanceof(v)) {
    return {
            TAG: /* A */0,
            _0: v
          };
  } else {
    return {
            TAG: /* B */1,
            _0: b$1
          };
  }
}

var A_or_b = {
  a: a,
  b: b$1,
  classify: classify$1
};

var x = {
  f: "foo"
};

var a$1 = 3.14;

export {
  x ,
  map_pair ,
  array ,
  Number_or_string ,
  a$1 as a,
  b ,
  c ,
  A_or_b ,
  
}
/*  Not a pure module */
