// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";

function map_pair(r, param) {
  return [
    r(param[0]),
    r(param[1])
  ];
}

let array = [
  3,
  "a"
];

function number(v) {
  return v;
}

function string(v) {
  return v;
}

function classify(v) {
  if (typeof v === "number") {
    return {
      TAG: "Number",
      _0: v
    };
  } else {
    return {
      TAG: "String",
      _0: v
    };
  }
}

let Number_or_string = {
  number: number,
  string: string,
  classify: classify
};

let a = 3.14;

let b = "hello";

let c = [
  a,
  b
];

Belt_Array.map(c, x => {
  console.log(x);
});

function a$1(v) {
  return v;
}

function b$1(v) {
  return v;
}

let $$instanceof = (function(a) {
      return  a instanceof globalThis.A;
      });

function classify$1(v) {
  if ($$instanceof(v)) {
    return {
      TAG: "A",
      _0: v
    };
  } else {
    return {
      TAG: "B",
      _0: b$1
    };
  }
}

let A_or_b = {
  a: a$1,
  b: b$1,
  classify: classify$1
};

let x = {
  f: "foo"
};

export {
  x,
  map_pair,
  array,
  Number_or_string,
  a,
  b,
  c,
  A_or_b,
}
/*  Not a pure module */
