// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Promise from "@rescript/core/src/Core__Promise.mjs";

function testEach(title, data, f) {
  test.each(data)(title + "(%#) %p", f);
}

function testEach2(title, data, f) {
  test.each(data)(title + "(%#) %p %p", f);
}

function testEach3(title, data, f) {
  test.each(data)(title + "(%#) %p %p %p", f);
}

function testEach4(title, data, f) {
  test.each(data)(title + "(%#) %p %p %p %p", f);
}

function awaitThen(pa, done, f) {
  Core__Promise.$$catch(pa.then(function (a) {
            f(a);
            done();
          }), done);
}

export {
  testEach ,
  testEach2 ,
  testEach3 ,
  testEach4 ,
  awaitThen ,
}
/* No side effect */
