// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.mjs";

function testEach(title, data, f) {
  test.each(data)("" + title + "(%#) %p", f);
}

function testEach2(title, data, f) {
  test.each(data)("" + title + "(%#) %p %p", f);
}

function testEach3(title, data, f) {
  test.each(data)("" + title + "(%#) %p %p %p", f);
}

function testEach4(title, data, f) {
  test.each(data)("" + title + "(%#) %p %p %p %p", f);
}

function awaitThen(pa, done, f) {
  $$Promise.$$catch(pa.then(function (a) {
            Curry._1(f, a);
            Curry._1(done, undefined);
          }), done);
}

export {
  testEach ,
  testEach2 ,
  testEach3 ,
  testEach4 ,
  awaitThen ,
}
/* No side effect */
