// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("rescript/lib/js/list.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function elements(s) {
  return List.sort_uniq(Caml_obj.caml_compare, s);
}

var M = {
  empty: /* [] */0,
  mem: List.mem,
  add: List.cons,
  elements: elements
};

exports.M = M;
/* No side effect */
